### ISSUE TITLE
Support for `pattern` keyword in string parameters

### ISSUE THREAD

**Issue by snorfalorpagus** [s-knibbs/dataclasses-jsonschema#15]
The OpenAPI 2.0 specification has support for a `pattern` argument to strings that allows you to specify a regular expression the input should conform to.

The example given as for a social security number:

```yaml
    ssn:
      type: string
      pattern: '^\d{3}-\d{2}-\d{4}$'
```

Support for this feature would be useful. I'm not sure how we can encode it in the dataclasses though?

Go has "tags" on struct fields for this kind of thing, e.g.

```go
type User struct {
    Name string `json:"name" xml:"name"`
}
```

Is there an equivalent in Python we could use?
